### ISSUE TITLE
Installation of plugin

### ISSUE THREAD

**Issue by DrOllyGomez** [nanoporetech/vbz_compression#11]
Hi

The section in the readme.md about installing the vbz plugin suggests that one visit the 'releases' section.
I've navigated to the releases section, and I see a bunch of links to the resources themselves, but no instructions on what to do with them.   
I am using Ubuntu release 20.04  x86_64.
Please tell me where I can find more instructions and which resource I need.
Many thanks in advance
Mike

**Comment by iiSeymour** [comment]
Hey @DrOllyGomez 

You will want to download [ont-vbz-hdf-plugin_1.0.1-1.focal_amd64.deb](https://github.com/nanoporetech/vbz_compression/releases/download/v1.0.1/ont-vbz-hdf-plugin_1.0.1-1.focal_amd64.deb) for Ubuntu 20.04 x86_64 and install with `dpkg -i ont-vbz-hdf-plugin_1.0.1-1.focal_amd64.deb`.

**Comment by DrOllyGomez** [comment]
Simplicity itself! And it solved the wider problem of processing some files as well!
Thankyou so much for responding so quickly... I can finish the day on the level :)
