### ISSUE TITLE
Error while running Artic's SARS-CoV-2 pipeline's Nanopolish on GridION fast5 output files 

### ISSUE THREAD

**Issue by SianSahadeo** [nanoporetech/vbz_compression#12]
Hi All, 
We just changed from using the ONT's MinION to their GridION for SARS-Cov-2 sequencing. Artic's ncov19 environment installed properly on the GridION as far as I can tell. After the sequencing run I tried running the pipeline. I was able to compile the fastq files for each barcode successfully. However, when running Nanopolish I got the attached error messages, and the consensus eventually built was the reference sequence. During this first run on the GridION I used the default high-accuracy basecalling option. I wondered if this might have been the issue so I rebasecalled it using the fast option but still the same error. I would appreciate any advice or help please. 
Thank you. 
[error.txt](https://github.com/nanoporetech/vbz_compression/files/6827476/error.txt)

**Comment by fbrennen** [comment]
Hi @SianSahadeo -- I see this error in your logs:

```
H5PL.c line 475 in H5PL__find(): can't open directory: /home/grid/miniconda3/envs/artic-ncov2019/lib/hdf5/plugin
```

Which suggests that your miniconda setup is causing issues finding the vbz plugin. You should hopefully already have the plugin installed on your GridION, in `/usr/local/hdf5/lib/plugin` -- if you don't you can download it from this github repo and install it. If the plugin isn't already installed on your GridION it's possible that will just fix your issue immediately, but if it doesn't then there are two different things you can try:

1. Manually copy the plugin into the location that hdf5-in-miniconda seems to be looking for it (`/home/grid/miniconda3/envs/artic-ncov2019/lib/hdf5/plugin`).
2. Set the environment variable `HDF5_PLUGIN_PATH` to point to the vbz plugin location (`/usr/local/hdf5/lib/plugin`). You will want to do this in the same console session you're using to run Nanopolish.

Please let us know how it goes!

**Comment by SianSahadeo** [comment]
Hi Forrest, 

Thank you so much for this. I followed your directions and it turns out the plugin was installed but, like you said, not in the correct place. I copied it over manually and this seems to have corrected the issue. My consensus fastas are building properly right now. Again, a thousand thanks for your time and advice. 

Nikita Sahadeo
