### ISSUE TITLE
Possible *small* improvement in compression ratios?

### ISSUE THREAD

**Issue by jkbonfield** [nanoporetech/vbz_compression#2]
I say possible, because I simply cannot get this to completely build nor to run (via release binaries) on the provided test data so it's hard to test on a large data set.  If you have better instructions they'd be welcomed.  Cmake just whinges it cannot find hdf5 despite having both library and headers installed.  Much hatred for cmake!  Why is it so mind bogglingly hard to adjust compile time hints?

However libvbz.a builds at least so I wrote my own driver tool to run on the raw data, obtained as follows:

```
# Dump the first signal data
h5dump -b NATIVE -o sig -d /read_0000173c-bf67-44e7-9a9c-1ad0bc728e74/Raw/Signal multi_fast5_zip.fast5
```

I now have "sig" which is 247254 bytes long.  It matches the hdf5 contents as expected:

```
h5ls -rv multi_fast5_vbz.fast5|grep -A5 Signal | head -6
/read_0000173c-bf67-44e7-9a9c-1ad0bc728e74/Raw/Signal Dataset {123627/123627}
    Location:  1:41515
    Links:     1
    Chunks:    {123627} 247254 bytes
    Storage:   247254 logical bytes, 104593 allocated bytes, 236.40% utilization
    Filter-0:  vbz-32020  {0, 2, 1, 1, 1}
```

My own method (from around 2014) achieves a little less (see [comp.c.txt](https://github.com/nanoporetech/vbz_compression/files/3443356/comp.c.txt)):

```
ubuntu@jkb-dev:~/vbz_compression/test_data$ ./comp < sig | ~/htscodecs/rans |wc -c
102681
```

The driver for vbz gives:

```
ubuntu@jkb-dev:~/vbz_compression/build$ ../test_data/a.out < ../test_data/sig|wc -c
104589
```

With a moving delta using MAXD of 32 I get this instead:

```
ubuntu@jkb-dev:~/vbz_compression/build$ ../test_data/a.out < ../test_data/sig|wc -c
103567
```

It's marginal, but trivial.  The main thing is to use `zigzag_encode` instead of `zigzag_delta_encode` and do a delta against a moving average where differences are close and a non-moving average when not.  Eg:

``` 
        unsigned int prev = 0;
        for (unsigned int i = 0; i < input_buffer.size(); i++) {
            unsigned int curr = input_buffer[i];
            int d = input_buffer[i] - prev;
            input_buffer[i] -= prev;

            prev = d > -MAXD && d < MAXD
                ? (prev+curr)/2
                : curr;
        }
```

(Yes I know it destroys the input buffer. It's just a hack to test it.)

MAXD is obviously a parameter that ought to be encoded in the data stream so it can be changed if the data changes without needing a new format.  Also (prev+curr)/2 is basically prev*P + curr*(1-P) where P=0.5, but this could also be parameterised and stored in the stream to permit more optimisation if we ever deem it worthwhile, although 0.5 works surprisingly well.

The overall difference is slight though - it's closer than I expected here.  I'm surprised as it made a big difference for my code.  Possibly this is something to do with the different varint implementation though.  Mine was crude (but effective as it's optimised for values mostly fitting in 1 byte rather than within 7 bits).

I haven't tried it on more than this one test file (averaging only 1.2% saving, or 2.6% using my own var-int code), but it's worth trying on other data sets to see if it helps anywhere, giving the completely trivial nature of the code.

**Comment by iiSeymour** [comment]
Thanks for the interest @jkbonfield. Can you confirm which compression options your `vbz` driver program uses?

To specify a hdf5 library location when building try the following:

```
$ HDF_LIBRARY_DIR=/usr/lib/x86_64-linux-gnu/hdf5/serial/
$ cmake -D ENABLE_CONAN=OFF \
 -D PKG_HDF5_C_INCLUDE_DIRS=${HDF_LIBRARY_DIR}/include \
 -D PKG_HDF5_C_LIBRARY_DIRS=${HDF_LIBRARY_DIR}/lib ..
```
Beside compression ratio, performance is a primary consideration. I wonder how much `prev = d > -MAXD && d < MAXD ? (prev+curr)/2: curr;`  will impact performance *(thinking vectorisation and branch prediction)*?

**Comment by jkbonfield** [comment]
My (initial) driver was using the same options in the README, so zigzag delta, integer size 2 (which matches the hdf5 unit size), v1 (although it falls through to v0 in the code anyway) and zstd 1.

Branch prediction is easy to address as you can just do branchless code.  Eg set the condition as a true/false and then use it in multiplications for the prev/curr sum.  Vectorisation maybe trickier as there is history to consider which makes it hard to do things in parallel.  Is that really the bottleneck of the entire thing though?  I'd have though things like Zstd swamps the encoding and decoding time along with the many layers of hdf5 data shuffling to go through.

As for building, thanks for the pointers.  It's getting closer, but my god you have to specify a lot of crap to get cmake to swallow hdf5.  Why doesn't it automatically look in /usr?  My packages are just the latest of everything that came with Ubuntu Bionic.  It's perhaps possible this is fixed in cmake 3.11, but I'm using 3.10 as 3.11 isn't shipped with the latest Ubuntu and I couldn't be bothered to download it from source and build a new cmake. (Sorry!)

Sadly it's still not quite working:

```
ubuntu@jkb-dev:~/vbz_compression/build$ cmake -D ENABLE_CONAN=OFF -D PKG_HDF5_C_INCLUDE_DIRS=/usr/include/hdf5/serial  -D PKG_HDF5_C_LIBRARY_DIRS=/usr/lib/x86_64-linux-gnu/hdf5/serial -D HDF5_CXX_INCLUDE_DIR=/usr/include/hdf5/serial -D HDF5_HL_INCLUDE_DIR=/usr/include/hdf5 -D HDF5_HL_LIBRARY=/usr/lib/x86_64-linux-gnu ..
-- Building version 1.0.0
CMake Error at cmake/ONTFindModuleHelpers.cmake:113 (message):
  Must specify LIBRARY, DEBUG_LIBRARY or RELEASE_LIBRARY
Call Stack (most recent call first):
  cmake/ONTFindModuleHelpers.cmake:252 (ont_create_library_target)
  cmake/FindHDF5.cmake:53 (ont_find_package_handle_library_components)
  CMakeLists.txt:99 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/ubuntu/vbz_compression/build/CMakeFiles/CMakeOutput.log".
```

Please consider this to be a user request for autotools instead. :-)

**Comment by iiSeymour** [comment]
> Is that really the bottleneck of the entire thing though?

When you have 100,000+ channels that need to be compressed in real-time it adds up. 

> I'd have thought things like Zstd swamps the encoding and decoding 

Zstd is pretty costly compared to the streamvbyte step so it's possible there is a win to be had here.

> Sadly it's still not quite working:

Okay, just one more flag!

```
-D CMAKE_BUILD_TYPE=Release
```

> Please consider this to be a user request for autotools instead.

Unfortunately, we have to support many different platforms which makes CMake worth the pain, sorry.

**Comment by jkbonfield** [comment]
> When you have 100,000+ channels that need to be compressed in real-time it adds up.
> 
> > I'd have thought things like Zstd swamps the encoding and decoding
> 
> Zstd is pretty costly compared to the streamvbyte step so it's possible there is a win to be had here.

You may get better speed calling FSE directly (assuming it's an external part of the zstd library) instead of going via the Zstd wrapper, as all it needs is entropy encoding and no dedup stage.  I don't have benchmarks on the speed differences though.   I do also have some scary SIMD variants of rANS (instead of tANS used in FSE) which entropy encode at maybe double the speed of FSE, but I wouldn't really say they're production quality - at least not compared to FSE.

> Okay, just one more flag!
> 
> ```
> -D CMAKE_BUILD_TYPE=Release
> ```

I'd already tried and it makes no difference.  I'm not sure why.

What OS does it work on and are you using vanilla installed packages or your own locally downloaded and compiled ones?

> > Please consider this to be a user request for autotools instead.
> 
> Unfortunately, we have to support many different platforms which makes CMake worth the pain, sorry.

That's also the whole remit of autotools (even Windows, although mingw rather than msvc).  However it trades needing a cmake executable and configuration for needing bourn shell and basic Unix tools.  Horses for courses there.

I don't particularly like autotools, but I've yet to find cmake packages that work first time!  For example, do you really need cmake 3.11 is it is simply the version you used and thus the version baked into the CMakeLists.txt?  Be aware that overspecifying the version number dramatically limits the number of OSes that'll be able to build the software without first having to download and compile yet another build system first.  (Eg Ubuntu Bionic ships cmake 3.10, RedHat 7.6 is way back in cmake 2.8 era)

**Comment by iiSeymour** [comment]
> You may get better speed calling FSE directly 

Great idea, looking at this now.

> I'd already tried and it makes no difference. I'm not sure why.

Okay, on vanilla bionic install this works for me with 3.10:

```
$ cmake -D ENABLE_CONAN=OFF -D CMAKE_PREFIX_PATH=/usr/lib/x86_64-linux-gnu/hdf5/serial/ -D ENABLE_PERF_TESTING=OFF -D ENABLE_PYTHON=OFF ..
```

>  Be aware that overspecifying the version number dramatically limits the number of OSes that'll be able to build the software without first having to download and compile yet another build system first.

Having a fixed version helps with build reproducibility and we build, package and distribute 3.11 internally which takes away most of this pain away.

**Comment by jkbonfield** [comment]
I can confirm that cmake command line works for me too.   Maybe it should be added to the documentation.

I also see that part of my problem was apparently cmake itself.  The above command does not work in my old build directory, but does work if I create a new one.  It appears cmake is caching brokenness somewhere and that state is breaking new attempts to build.  Ewww.

Anyway, thanks for the help in getting it built, officially rather than via my homebrew hacks.

**Comment by iiSeymour** [comment]
Glad it's building now, I'll update the documentation.

I've published some [Python bindings](https://github.com/iiSeymour/pyfse) for FSE and done some [benchmarking](https://gist.github.com/iiSeymour/76fd14c6062c19378ec6436ca4dc7374) on 1000 reads.   

|   | Time (s) | Compression (%) |
| ------------- | ------------- | ------------- |
|gzip|4.056 | 56.13 |
|zstd|1.002 | 63.98 |
|fse|0.690|64.81 |
|svb + fse|0.632 | 41.53 |
|svb + zstd|0.431 | 37.00 |
|svb |0.241 | 63.53 |

So `streamvbyte + zstd` is still on top however this is using the simple API so it's possible that [FSE_compress2](https://github.com/Cyan4973/FiniteStateEntropy/blob/dev/lib/fse.h#L125) could perform better.

**Comment by jkbonfield** [comment]
I take it smaller percentage is better compression here.  Curious zstd is both faster and smaller than FSE.  I wonder what it's finding to deduplicate in these data streams.  Anyway, good to test.  Thanks and sorry it didn't help.

**Comment by iiSeymour** [comment]
Smaller is better, yes. It's interesting that `fse` is faster by itself than `zstd` but not when combined with `svb`.

I ran `comp` on the same reads and got a compression of ~50%. I'm not sure where to get `rans` from as I checked out and built `htscodecs` but didn't end up with a binary `rans`?

**Comment by jkbonfield** [comment]
On Thu, Aug 01, 2019 at 04:44:11AM -0700, Chris Seymour wrote:
> I ran `comp` on the same reads and got a compression of ~50%. I'm not sure where to get `rans` from as I checked out and built `htscodecs` but didn't end up with a binary `rans`?

That's probably just my local name (it may well have been a.out!).
However the tests directory has rans4x8 and rans4x16pr test binaries,
with the latter being the more recent.  It's purely an entropy encoder
/ decoder.

James

-- 
James Bonfield (jkb@sanger.ac.uk)
The Sanger Institute, Hinxton, Cambs, CB10 1SA


-- 
 The Wellcome Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is 215 Euston Road, London, NW1 2BE.

**Comment by iiSeymour** [comment]
Okay so with `rans4x16pr` on the same 1000 reads, I get a mean compression of **36.38%** vs **37%** for `svb + zstd`. On a second set, **38.28%** vs **38.41%** so it's looking good :+1: The bad news is the run time is north of 30 seconds.

**Comment by jkbonfield** [comment]
Ah well, not good then.  I'm guessing comp+zstd will be much the same as comp+rANS, but also equally slow.

I'll close the issue, but it's always fun to explore different compression methods. (Or is that just me? :-)).
