### ISSUE TITLE
issue with conan while running make command

### ISSUE THREAD

**Issue by prabakarraj** [nanoporetech/vbz_compression#24]
I am trying to install tailfindr R package. Before that I am trying to install VBZ plugin. I was able to download the source code and cmake, But running make command, its prompting error.

[  9%] Performing configure step for 'streamvbyte'
[ 13%] Built target hdf_test_utils
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
-- Building version
CMake Warning at CMakeLists.txt:14 (project):
  VERSION keyword not followed by a value or was followed by a value that
  expanded to nothing.

CMake Error at CMakeLists.txt:90 (include):
  include could not find requested file:

    conan

CMake Error at CMakeLists.txt:128 (conan_cmake_run):
  Unknown CMake command "conan_cmake_run".

-- Configuring incomplete, errors occurred!
See also "/apps/Tailfindr/VBZ1/vbz_compression-1.0.2/build/streamvbyte/src/streamvbyte-build/CMakeFiles/CMakeOutput.log".
make[2]: *** [CMakeFiles/streamvbyte.dir/build.make:91: streamvbyte/src/streamvbyte-stamp/streamvbyte-configure] Error 1
make[1]: *** [CMakeFiles/Makefile2:944: CMakeFiles/streamvbyte.dir/all] Error 2
make: *** [Makefile:166: all] Error 2

I have followed exact step provided in the page.

Because of this, Tailfindr package provide N/A values. kindly assist me on this. Thanks for your assistance in advance.

**Comment by jorj1988** [comment]
Hi @prabakarraj ,

Is there a binary artifact that meets your needs in the latest release? If so, I would recomend you use that.

If not, what is the exact command you ran to generate the above error, and what is your environment?

Thanks,
- George

**Comment by prabakarraj** [comment]
Hi George,

I'm Not sure about the binary artifacts,

I just downloaded the source tar file using wget command and untar the file and ran below commands 
> git submodule update --init
> mkdir build
> cd build
> cmake -D CMAKE_BUILD_TYPE=Release -D ENABLE_CONAN=OFF -D ENABLE_PERF_TESTING=OFF -D ENABLE_PYTHON=OFF ..
> make -j

I am getting the error as output for make command.

Thanks
Prabakar

**Comment by jorj1988** [comment]
Ok,

What's your OS and architecture?

Thanks,
- George

**Comment by prabakarraj** [comment]
Operating System: Amazon Linux 2
Architecture: x86-64

**Comment by jorj1988** [comment]
Ok,

there isnt a package compatible with that version of linux i believe.

Whats the output from your `cmake` command, the above is the output from your `make` command?

Thanks,
- George

**Comment by prabakarraj** [comment]
This is the output of cmake command,

#cmake -D CMAKE_BUILD_TYPE=Release -D ENABLE_CONAN=OFF -D ENABLE_PERF_TESTING=OFF -D ENABLE_PYTHON=OFF ..

fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
-- Building version
CMake Warning at CMakeLists.txt:14 (project):
  VERSION keyword not followed by a value or was followed by a value that
  expanded to nothing.

-- Configuring done
-- Generating done
-- Build files have been written to: /apps/Tailfindr/VBZ1/vbz_compression-1.0.2/build

Thanks
Prabakar

**Comment by jorj1988** [comment]
Hello, this seems like a problem:

```fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).```

What directory are you running the cmake command from?

**Comment by prabakarraj** [comment]
I'm running cmake command on the /vbz_compression-1.0.2/build ( typically untar directory of VBZ and then build directory).

**Comment by jorj1988** [comment]
OK,

At least some of your issues will stem from downloading the source from the release page - the steps on the readme.md are intended to be run on a git checkout in order to update the git submodules.

Can you try to clone the project using git, and retry the steps on the readme?

Thanks,
- George

**Comment by prabakarraj** [comment]
Hi George,

Installation using git clone worked well. Thank you for your assistance.

Thanks
Prabakar
