### ISSUE TITLE
vbz_compression and added signal data e.g. Prob mod calls.

### ISSUE THREAD

**Issue by callumparr** [nanoporetech/vbz_compression#6]
Sorry if this is naiive question. 

If I were to use software like tombo or nanopolish that adds additional information to the original raw fast5 file, is this something that would be lost if vbz compression is applied and then extracted later?

I am also using basecall.py script from taiyaki that can output probability of modification. Will this information be lost during compression?

**Comment by jorj1988** [comment]
It depends on how these tools work internally - if they copy the original file then add to it the vbz compression will be preserved.

The best way to tell is to open the file up in HdfView and check the compression options on the dataset once its been through any tool you choose to use.
