### ISSUE TITLE
Conda support

### ISSUE THREAD

**Issue by mmiladi** [nanoporetech/vbz_compression#7]
Hi,

I was wondering if the vbz compression is supported or going to be supported in conda or as binary files.
Currently, we have difficulty running nanopolish, because we cannot use the offered package managers on our systems to install the vbz compression.

Best,
-M

**Comment by iiSeymour** [comment]
Hi @mmiladi, we will get some prebuilt binaries added to the release page.

**Comment by mmiladi** [comment]
That would be great @iiSeymour !

**Comment by iiSeymour** [comment]
Hey @mmiladi the release page now has a couple of archive builds with just `libvbz_hdf_plugin.so` inside. 

 - `ont-vbz-hdf-plugin-1.0.0-Linux-x86_64.tar.gz`
 - `ont-vbz-hdf-plugin-1.0.0-Linux-aarch64.tar.gz`

Either copy the plugin to the standard location - `/usr/local/hdf5/lib/plugin` or use the environment variable `HDF5_PLUGIN_PATH` for a custom location.

**Comment by mmiladi** [comment]
Awesome! Thanks @iiSeymour
