### ISSUE TITLE
Free software license?

### ISSUE THREAD

**Issue by nileshpatra** [nanoporetech/vbz_compression#8]
Hi,
the `license.txt` says: 
```
These are available on the Oxford Nanopore Technologies website (https://nanoporetech.com) and
also inthe included pdf file, "Nanopore Community TCs 09 September 2016.pdf".
```

I can't seem to find such a document anywhere on the site. Is [this](https://nanoporetech.com/sites/default/files/s3/terms/Nanopore-Community-TCs-30-March-2017.pdf) the document it talks about?

On reading this - this looks 'non-free'. Could you clarify if it is?

We actually wanted to vendor this software in Debian GNU/Linux - since this is a dependency of several biomedical softwares. If this is non-free : would you mind switching the license to a free software license?

**Comment by nileshpatra** [comment]
@iiSeymour @rmp would you mind clarifying this?

**Comment by iiSeymour** [comment]
Hi @nileshpatra 

Thanks for bringing this to our attention - I will change the license to the mozilla public license tomorrow.

Regards,

Chris.

**Comment by nileshpatra** [comment]
> Thanks for bringing this to our attention - I will change the license to the mozilla public license tomorrow.

@iiSeymour could you please do the needful now? :-)

**Comment by iiSeymour** [comment]
Relicensed, tagged and released.
